### PR TITLE
Travis buildx

### PR DESCRIPTION
**Pull request by alok123t**
Updated the Travis build script to support multi-arch configuration #251 
This PR
- installs the latest version of docker and enables experimental flag for buildx
- uses buildx for building

### CODE REVIEW

**Comment by alok123t** [comment]
Currently, `commons/java/openjdk11` which has been merged, successfully builds

If we want to have `docker build` and `docker buildx` build as separate, I can make the changes for buildx in `scripts/travis/travis-buildx.sh`

**Comment by neo-apz** [comment]
@alok123t thanks for the PR. I think it's better to have different platforms as parallel builds rather than one build that creates all three images (similar to the thing we did for each workload).
Also as these can take a long time, it's better to have the Travis wait command. Was there a particular reason for which you removed it?
Then perhaps we can comment out the older versions of the images and just keep the last updated version in the travis build matrix, the old ones can be updated and pushed manually if needed.

**Comment by alok123t** [comment]
@neo-apz buildx builds all the architectures in parallel [code-link](https://github.com/parsa-epfl/cloudsuite/blob/39ada35bf4e8aacbf7f6bacfd1c18f50752bee8b/scripts/travis/travis.sh#L19)

I was thinking we can do it the following way
`- DH_REPO="cloudsuite/java" IMG_TAG="openjdk11" DF_PATH="./commons/java/openjdk11" DBX_PLATFORM=amd64,arm64,riscv64`
If we do it as separate builds for each platform, then we would have to create a docker manifest, based on the success/failure of each travis build. While buildx does this automatically. Should I make this change for all builds in the env matrix? 

Also, do we want to have docker build for older tags and buildx for workloads which support multi-arch. Or use buildx for all workloads and have `amd64` for previous versions and `amd64,arm64,riscv64` for supported ones.

Travis wait doesn't seem to work as expected, I am debugging to check why it fails for buildx (it works fine for build). The `travis.sh` scripts exits after running buildx command.

**Comment by neo-apz** [comment]
@alok123t OK, then let's try to make it work the way it is. My only concern is that building for multiple platforms takes in one build takes a lot of time and it might surpass the travis limit (which I think is one hour).

I believe we should drop the older versions altogether, their images are already built and available on dockerhub. So let's just focus on the latest version.

What's the problem with "travis wait"? We need to have it, otherwise, things won't work.

**Comment by alok123t** [comment]
@neo-apz travis has a per-job limit of 50 mins [link-travis](https://docs.travis-ci.com/user/customizing-the-build#build-timeouts), there is no overall limit
I will comment the older versions for each workload in this PR
Should I follow the below approach for each job and update the PR?
`- DH_REPO="cloudsuite/java" IMG_TAG="openjdk11" DF_PATH="./commons/java/openjdk11" DBX_PLATFORM=amd64,arm64,riscv64`

**Comment by alok123t** [comment]
Looks like some jobs on travis are failing. I think most of them are addressed in the other open PRs. Once they are merged, we can comment out the older versions and can have a green tick on travis.

Buildx seems to work fine and the build time for each job is <5mins for most of them
Also, I have added travis wait

**Comment by neo-apz** [comment]
Thanks for the update. Based on the logs there are major problems (not related to other PRs). Check out this one that tries to build Java: https://travis-ci.org/github/parsa-epfl/cloudsuite/jobs/687596667

**Comment by alok123t** [comment]
I have removed the older versions which are not building. Looks like re-building java for risc worked. Not sure why there was an issue earlier, as the same code was building successfully.

**Comment by neo-apz** [comment]
OK, this looks good to me; I will merge it soon after a few tests.
We need to bring back the commented build lines for each workload separately.
Can you please rebase all the other PRs opened by you when this is merged so that they have the updated build script?
Thanks!

**Pull request merged**
