### PR TITLE
Updated travis to include riscv for datacaching server

### PR DESCRIPTION
**Pull request by komal1204**

### CODE REVIEW

**Comment by yunho-oh** [comment]
Thanks for this PR.
It seems that we can simply merge this PR if the travis build passes. Is there something I should do for the travis build?

**Comment by komal1204** [comment]
> Thanks for this PR.
> It seems that we can simply merge this PR if the travis build passes. Is there something I should do for the travis build?

Hello,

Yes this can be merged, travis build is failing because it is getting cancelled .
image

This is the issue in all the 4 builds that have failed for travis.

This is a similar issue for travis build as in the Django PR. #265 

For the MySql Pr too which is already merged but image is not uploaded to docker hub - travis build needs to be re-triggered as i am able to build it successfully only in travis it fails.

Thanks,
Komal

**Comment by yunho-oh** [comment]
Hi @komal1204 

I am looking into the travis build issue, but I could not find the reason yet. 
I will keep it posted.

**Comment by yunho-oh** [comment]
It seems that the slowdown of the travis builds was a temporal problem. Now a build is done much faster than yesterday.

However, regardless of the speed of the build, it still fails. Please let me know if anything I can help with. Then, I will do it tomorrow.

**Comment by yunho-oh** [comment]
Hi @komal1204 

Please refer to the changes in #265.
Please try to apply the same change to this PR and re-trigger the travis build.

**Comment by komal1204** [comment]
> Hi @komal1204
> 
> Please refer to the changes in #265.
> Please try to apply the same change to this PR and re-trigger the travis build.

Hello, 
Thanks, will take a look and try to incorporate those changes.

**Comment by komal1204** [comment]
Hello @yunho-oh ,

I have rebased and updated this PR, the travis build should succeed now.

Thanks,
Komal

**Review by yunho-oh — APPROVED** [review]

**Pull request merged**
