### PR TITLE
changed hadoop master listening address to 0.0.0.0

### PR DESCRIPTION
**Pull request by chapaith**
In file `cloudsuite/commons/hadoop/2.10.1/files/entrypoint.sh`,  I have changed the listening address to `0.0.0.0` from `127.0.1.1`. I am confused about how to expose the ports so, any insight into that will be very helpful for me.

### CODE REVIEW

**Comment by jagannathkumarbits** [comment]
Dear sir,
After doing a lot of research and hard work, I understood the issues and wrote the solution on two different machines, that is master and slave, in python, and it is working fine now, and  I do not have a proper understanding of Shell Scripting that's why I wrote the solution in python, however, it has been allowing to write the solution in python, c..., I would request to review the solution by clicking on given below link.

This is what final contribution from my end, thanks for giving me this opportunity.

https://drive.google.com/file/d/1YJeF5A1QQp8tmSYVq0QNp0jS2fwpNy7W/view?usp=sharing

**Comment by jagannathkumarbits** [comment]
Dear sir,
please reply about this solution whether is it fine??

**Comment by Xusine1131** [comment]
Hello,

Thanks for your interest in this PR and your code. However, I don't think your code is related to the PR. Your code opened a socket listening on 0.0.0.0, but it is your personal socket, not the socket of Hadoop. We are expecting a small change to Hadoop's configuration file which influences its listening IP. 

Regards

**Comment by Xusine1131** [comment]
We are cleaning the PR, so we decide to close it. Feel free to reopen it if you need.

**Pull request closed without merging**
