### PR TITLE
Fix data-analytics build

### PR DESCRIPTION
**Pull request by ajaygk95**

### CODE REVIEW

**Comment by ajaygk95** [comment]
Hello,

Data-analytics workload build is failing in travis.

This PR fixes the build issue

**Comment by yunho-oh** [comment]
Thank you for the new PR #270. 
I will look into this PR first and come back to #261 and #265. 
After that, I will work on #268.

**Review by yunho-oh — APPROVED** [review]
I reviewed the changes and checked that this PR works.

**Comment by ajaygk95** [comment]
Hello @yunho-oh ,

Can you please merge this PR

**Comment by yunho-oh** [comment]
> Hello @yunho-oh ,
> 
> Can you please merge this PR

Hi @ajaygk95 

Yes, I will do it asap. I am seeking one more reviewer in our lab to fulfill the following requirement to merge PRs.
"At least 2 approving reviews are required by reviewers with write access."

**Review by neo-apz — APPROVED** [review]

**Pull request merged**
