### PR TITLE
Multivm web search

### PR DESCRIPTION
**Pull request by alok123t**

### CODE REVIEW

**Comment by pradeepk5** [comment]
Thanks for the PR,
I could able to build the images, 
However, when running the server, I get these errors

```
/usr/src/solr-5.2.1/bin/solr: line 1156: ps: command not found
```
and 
```
WARN  - 2020-05-20 10:39:14.895; org.apache.solr.util.SolrCLI; Request to http://localhost:8983/solr/admin/info/system failed due to: Connection refused (Connection refused), sleeping for 5 seconds before re-trying the request ...
```

**Comment by VamshiMuthineni** [comment]
the issue was because ps was not installed by default in debian. fixed now.

**Comment by pradeepk5** [comment]
When running the server image, I am getting the following error, which should be related to the port 8983 is not opened.
```
Waiting to see Solr listening on port 8983 [\]  Still not seeing Solr listening on 8983 after 30 seconds!
tail: cannot open '/usr/src/solr-5.2.1/server/logs/solr.log' for reading: No such file or directory
    
Found 1 Solr nodes: 

Solr process 61 from /usr/src/solr-5.2.1/bin/solr-8983.pid not found.
WARN  - 2020-05-21 10:48:11.885; org.apache.solr.util.SolrCLI; Request to http://localhost:8983/solr/admin/info/system failed due to: Connection refused (Connection refused), s
leeping for 5 seconds before re-trying the request ...
Exception in thread "main" java.net.ConnectException: Connection refused (Connection refused)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
```

**Comment by VamshiMuthineni** [comment]
I was able to run server image without any issues using the following command(from the updated docs).
docker run -it --name server --volumes-from ${dataset container id} --net host cloudsuite/web-search:server 12g 1
Can you check if you're doing the same?

**Comment by pradeepk5** [comment]
> I was able to run server image without any issues using the following command(from the updated docs).
> docker run -it --name server --volumes-from ${dataset container id} --net host cloudsuite/web-search:server 12g 1
> Can you check if you're doing the same?
Yes, I am doing the same.

**Comment by neo-apz** [comment]
I also experience the same thing:

```
Waiting to see Solr listening on port 8983 [/]  Still not seeing Solr listening on 8983 after 30 seconds!
tail: cannot open '/usr/src/solr-5.2.1/server/logs/solr.log' for reading: No such file or directory
    
Found 1 Solr nodes: 

Solr process 64 from /usr/src/solr-5.2.1/bin/solr-8983.pid not found.
WARN  - 2020-05-22 11:15:22.953; org.apache.solr.util.SolrCLI; Request to http://localhost:8983/solr/admin/info/system failed due to: Connection refused (Connection refused), sleeping for 5 seconds before re-trying the request ...
Exception in thread "main" java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:220)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:139)
	at org.apache.solr.util.SolrCLI.getJson(SolrCLI.java:527)
	at org.apache.solr.util.SolrCLI.getJson(SolrCLI.java:471)
	at org.apache.solr.util.SolrCLI.getJson(SolrCLI.java:481)
	at org.apache.solr.util.SolrCLI.getZkHost(SolrCLI.java:1156)
	at org.apache.solr.util.SolrCLI$CreateCollectionTool.runTool(SolrCLI.java:1210)
	at org.apache.solr.util.SolrCLI.main(SolrCLI.java:215)
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
/entrypoint.sh: line 13: cd: /usr/src/solr_cores/cloudsuite_web_search*: No such file or directory
'/download/data' -> './data'
'/download/data/index' -> './data/index'
'/download/data/index/_ne_Lucene50_0.tim' -> './data/index/_ne_Lucene50_0.tim'
'/download/data/index/segments_an' -> './data/index/segments_an'
'/download/data/index/_ne.nvd' -> './data/index/_ne.nvd'
'/download/data/index/write.lock' -> './data/index/write.lock'
'/download/data/index/_ne.fnm' -> './data/index/_ne.fnm'
'/download/data/index/_ne.fdx' -> './data/index/_ne.fdx'
'/download/data/index/_ne_Lucene50_0.pos' -> './data/index/_ne_Lucene50_0.pos'
'/download/data/index/_ne_Lucene50_0.pay' -> './data/index/_ne_Lucene50_0.pay'
'/download/data/index/_ne.si' -> './data/index/_ne.si'
'/download/data/index/_ne.nvm' -> './data/index/_ne.nvm'
'/download/data/index/_ne_Lucene50_0.doc' -> './data/index/_ne_Lucene50_0.doc'
'/download/data/index/_ne.fdt' -> './data/index/_ne.fdt'
'/download/data/index/_ne_Lucene50_0.tip' -> './data/index/_ne_Lucene50_0.tip'
'/download/data/tlog' -> './data/tlog'
'/download/data/tlog/tlog.0000000000000000380' -> './data/tlog/tlog.0000000000000000380'
=================================
Index Node IP Address: 10.90.36.55 172.17.0.1
=================================

Starting Solr in SolrCloud mode on port 8983 from /usr/src/solr-5.2.1/server

OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Unrecognized VM option 'UseParNewGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by neo-apz** [comment]
Any update on this?
The error is still present.

**Comment by neo-apz** [comment]
> Any update on this?
> The error is still present.

@alok123t @VamshiMuthineni

**Comment by alok123t** [comment]
@neo-apz @pradeepk5 I have graduated this May from Stony Brook and will not be able to actively work on the project. @VamshiMuthineni @ajaygk95 and @komal1204 will be addressing the comments soon. 
Thank you for your suggestions :)

**Comment by neo-apz** [comment]
OK, thanks @alok123t!

**Comment by VamshiMuthineni** [comment]
I'm sorry for the delay in response. My summer internship has started and I couldn't get free time to work on this. 

The solr version was not supporting Java version. so moved to solr-6.6.6. It's working fine now.

**Comment by neo-apz** [comment]
Thanks @VamshiMuthineni for your contribution. It seems to be working now.

**Pull request merged**
