### PR TITLE
Media Streaming and Data-serving for riscv

### PR DESCRIPTION
**Pull request by ajaygk95**

### CODE REVIEW

**Comment by ajaygk95** [comment]
Please merge #268 before this

**Comment by ajaygk95** [comment]
Hello @yunho-oh ,

Can you please review this PR.

Thanks.

**Comment by yunho-oh** [comment]
Will get back to you regarding this PR on Monday.

**Comment by yunho-oh** [comment]
Hi, @ajaygk95 

While building cloudsuite/media-streaming:dataset, I am facing the following error. I also tried another machine, but the same error occurs. 

 => ERROR [linux/arm64  2/10] RUN apt-get update && apt-get install make wget bu  23.1s
 => CANCELED [linux/riscv64  2/10] RUN apt-get update && apt-get install make wg  21.4s
 => [linux/amd64  2/10] RUN apt-get update && apt-get install make wget build-es  20.7s
 => CANCELED [linux/amd64  3/10] RUN wget https://downloads.xiph.org/releases/ogg  0.8s
...

#18 22.86 Error while loading /usr/sbin/dpkg-split: No such file or directory
#18 22.87 Error while loading /usr/sbin/dpkg-deb: No such file or directory
#18 22.87 dpkg: error processing archive /var/cache/apt/archives/perl-base_5.28.1-6+deb1                                                                                                                         0u1_arm64.deb (--unpack):
#18 22.87  dpkg-deb --control subprocess returned error exit status 1
#18 22.88 Errors were encountered while processing:
#18 22.88  /var/cache/apt/archives/perl-base_5.28.1-6+deb10u1_arm64.deb
#18 22.98 E: Sub-process /usr/bin/dpkg returned an error code (1)
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/dev/.buildki                                                                                                                         t_qemu_emulator /bin/sh -c apt-get update && apt-get install make wget build-essential c                                                                                                                         make -y]: exit code: 100

However, the travis build for the same image was successful. I will try to build it again.
If you have an idea about it, please let me know. That would be helpful.

**Comment by yunho-oh** [comment]
> Hi, @ajaygk95
> 
> While building cloudsuite/media-streaming:dataset, I am facing the following error. I also tried another machine, but the same error occurs.
> 
> => ERROR [linux/arm64 2/10] RUN apt-get update && apt-get install make wget bu 23.1s
> => CANCELED [linux/riscv64 2/10] RUN apt-get update && apt-get install make wg 21.4s
> => [linux/amd64 2/10] RUN apt-get update && apt-get install make wget build-es 20.7s
> => CANCELED [linux/amd64 3/10] RUN wget https://downloads.xiph.org/releases/ogg 0.8s
> ...
> 
> ## #18 22.86 Error while loading /usr/sbin/dpkg-split: No such file or directory
> #18 22.87 Error while loading /usr/sbin/dpkg-deb: No such file or directory
> #18 22.87 dpkg: error processing archive /var/cache/apt/archives/perl-base_5.28.1-6+deb1 0u1_arm64.deb (--unpack):
> #18 22.87 dpkg-deb --control subprocess returned error exit status 1
> #18 22.88 Errors were encountered while processing:
> #18 22.88 /var/cache/apt/archives/perl-base_5.28.1-6+deb10u1_arm64.deb
> #18 22.98 E: Sub-process /usr/bin/dpkg returned an error code (1)
> failed to solve: rpc error: code = Unknown desc = executor failed running [/dev/.buildki t_qemu_emulator /bin/sh -c apt-get update && apt-get install make wget build-essential c make -y]: exit code: 100
> 
> However, the travis build for the same image was successful. I will try to build it again.
> If you have an idea about it, please let me know. That would be helpful.

My own build issue is done. Never mind. I keep testing this PR.

**Comment by ajaygk95** [comment]
> > Hi, @ajaygk95
> > While building cloudsuite/media-streaming:dataset, I am facing the following error. I also tried another machine, but the same error occurs.
> > => ERROR [linux/arm64 2/10] RUN apt-get update && apt-get install make wget bu 23.1s
> > => CANCELED [linux/riscv64 2/10] RUN apt-get update && apt-get install make wg 21.4s
> > => [linux/amd64 2/10] RUN apt-get update && apt-get install make wget build-es 20.7s
> > => CANCELED [linux/amd64 3/10] RUN wget https://downloads.xiph.org/releases/ogg 0.8s
> > ...
> > ## #18 22.86 Error while loading /usr/sbin/dpkg-split: No such file or directory
> > #18 22.87 Error while loading /usr/sbin/dpkg-deb: No such file or directory
> > #18 22.87 dpkg: error processing archive /var/cache/apt/archives/perl-base_5.28.1-6+deb1 0u1_arm64.deb (--unpack):
> > #18 22.87 dpkg-deb --control subprocess returned error exit status 1
> > #18 22.88 Errors were encountered while processing:
> > #18 22.88 /var/cache/apt/archives/perl-base_5.28.1-6+deb10u1_arm64.deb
> > #18 22.98 E: Sub-process /usr/bin/dpkg returned an error code (1)
> > failed to solve: rpc error: code = Unknown desc = executor failed running [/dev/.buildki t_qemu_emulator /bin/sh -c apt-get update && apt-get install make wget build-essential c make -y]: exit code: 100
> > However, the travis build for the same image was successful. I will try to build it again.
> > If you have an idea about it, please let me know. That would be helpful.
> 
> My own build issue is done. Never mind. I keep testing this PR.

Hello @yunho-oh ,

Few of the jobs are randomly failing with the same error.

Please let me know, how did you fix the issue.

Thanks

**Comment by yunho-oh** [comment]
> > > Hi, @ajaygk95
> > > While building cloudsuite/media-streaming:dataset, I am facing the following error. I also tried another machine, but the same error occurs.
> > > => ERROR [linux/arm64 2/10] RUN apt-get update && apt-get install make wget bu 23.1s
> > > => CANCELED [linux/riscv64 2/10] RUN apt-get update && apt-get install make wg 21.4s
> > > => [linux/amd64 2/10] RUN apt-get update && apt-get install make wget build-es 20.7s
> > > => CANCELED [linux/amd64 3/10] RUN wget https://downloads.xiph.org/releases/ogg 0.8s
> > > ...
> > > ## #18 22.86 Error while loading /usr/sbin/dpkg-split: No such file or directory
> > > #18 22.87 Error while loading /usr/sbin/dpkg-deb: No such file or directory
> > > #18 22.87 dpkg: error processing archive /var/cache/apt/archives/perl-base_5.28.1-6+deb1 0u1_arm64.deb (--unpack):
> > > #18 22.87 dpkg-deb --control subprocess returned error exit status 1
> > > #18 22.88 Errors were encountered while processing:
> > > #18 22.88 /var/cache/apt/archives/perl-base_5.28.1-6+deb10u1_arm64.deb
> > > #18 22.98 E: Sub-process /usr/bin/dpkg returned an error code (1)
> > > failed to solve: rpc error: code = Unknown desc = executor failed running [/dev/.buildki t_qemu_emulator /bin/sh -c apt-get update && apt-get install make wget build-essential c make -y]: exit code: 100
> > > However, the travis build for the same image was successful. I will try to build it again.
> > > If you have an idea about it, please let me know. That would be helpful.
> > 
> > 
> > My own build issue is done. Never mind. I keep testing this PR.
> 
> Hello @yunho-oh ,
> 
> Few of the jobs are randomly failing with the same error.
> 
> Please let me know, how did you fix the issue.
> 
> Thanks

My issue was not related to the travis build. I am doing the regression test with my machine. I just re-installed docker and binfmt.

**Comment by ajaygk95** [comment]
> > > > Hi, @ajaygk95
> > > > While building cloudsuite/media-streaming:dataset, I am facing the following error. I also tried another machine, but the same error occurs.
> > > > => ERROR [linux/arm64 2/10] RUN apt-get update && apt-get install make wget bu 23.1s
> > > > => CANCELED [linux/riscv64 2/10] RUN apt-get update && apt-get install make wg 21.4s
> > > > => [linux/amd64 2/10] RUN apt-get update && apt-get install make wget build-es 20.7s
> > > > => CANCELED [linux/amd64 3/10] RUN wget https://downloads.xiph.org/releases/ogg 0.8s
> > > > ...
> > > > ## #18 22.86 Error while loading /usr/sbin/dpkg-split: No such file or directory
> > > > #18 22.87 Error while loading /usr/sbin/dpkg-deb: No such file or directory
> > > > #18 22.87 dpkg: error processing archive /var/cache/apt/archives/perl-base_5.28.1-6+deb1 0u1_arm64.deb (--unpack):
> > > > #18 22.87 dpkg-deb --control subprocess returned error exit status 1
> > > > #18 22.88 Errors were encountered while processing:
> > > > #18 22.88 /var/cache/apt/archives/perl-base_5.28.1-6+deb10u1_arm64.deb
> > > > #18 22.98 E: Sub-process /usr/bin/dpkg returned an error code (1)
> > > > failed to solve: rpc error: code = Unknown desc = executor failed running [/dev/.buildki t_qemu_emulator /bin/sh -c apt-get update && apt-get install make wget build-essential c make -y]: exit code: 100
> > > > However, the travis build for the same image was successful. I will try to build it again.
> > > > If you have an idea about it, please let me know. That would be helpful.
> > > 
> > > 
> > > My own build issue is done. Never mind. I keep testing this PR.
> > 
> > 
> > Hello @yunho-oh ,
> > Few of the jobs are randomly failing with the same error.
> > Please let me know, how did you fix the issue.
> > Thanks
> 
> My issue was not related to the travis build. I am doing the regression test with my machine. I just re-installed docker and binfmt.

Few jobs in the travis build for #265 are failing with a similar error. https://travis-ci.org/github/parsa-epfl/cloudsuite/jobs/749156915

**Comment by yunho-oh** [comment]
I am not sure this comment helps us.
In parsa-epfl/cloudsuite:.travis.yml, we may try to replace 
**'docker run --rm --privileged multiarch/qemu-user-static --reset -p yes'**
to
**docker run --privileged --rm tonistiigi/binfmt --install all**
I am using it for testing compile of multi-architecture docker images.

**Comment by ajaygk95** [comment]
> I am not sure this comment helps us.
> In parsa-epfl/cloudsuite:.travis.yml, we may try to replace
> **'docker run --rm --privileged multiarch/qemu-user-static --reset -p yes'**
> to
> **docker run --privileged --rm tonistiigi/binfmt --install all**
> I am using it for testing compile of multi-architecture docker images.

I can give this a try, I will change the `.travis.yml` and monitor the build

**Comment by yunho-oh** [comment]
I have tested this PR and observed that both workloads are running normally.
Once the travis build successes, I will merge this PR.

**Comment by yunho-oh** [comment]
I keep watching the travis build and re-triggering failed builds. So, please do not touch the build as of now. I will deal with them and merge this PR soon.

**Review by yunho-oh — APPROVED** [review]

**Pull request merged**
