### PR TITLE
Cassandra and Memcached for riscv

### PR DESCRIPTION
**Pull request by ajaygk95**

### CODE REVIEW

**Comment by yunho-oh** [comment]
Hi @ajaygk95 

Thank you for the PR. 
I have tested it with a single server container and a single client.
In my test with an x86 machine, the following message is showing. 
Could you please check it? 

----------------------------------------------------------------------
Warning: Cannot create directory at `/home/cassandra/.cassandra`. Command history will not be saved.

Traceback (most recent call last):
  File "/opt/cassandra/bin/cqlsh.py", line 2443, in <module>
    main(*read_options(sys.argv[1:], os.environ))
  File "/opt/cassandra/bin/cqlsh.py", line 2421, in main
    encoding=options.encoding)
  File "/opt/cassandra/bin/cqlsh.py", line 485, in __init__
    load_balancing_policy=WhiteListRoundRobinPolicy([self.hostname]),
  File "/opt/cassandra/bin/../lib/cassandra-driver-internal-only-3.11.0-bb96859b.zip/cassandra-driver-3.11.0-bb96859b/cassandra/policies.py", line 417, in __init__
socket.gaierror: [Errno -2] Name or service not known
Cannot connect to the seed server. Trying again...

**Comment by ajaygk95** [comment]
Hello @yunho-oh ,

The cassandra dockerfile does not start the cassandra service. 
This docker image will be used as a base while building other workloads (Ex : Data Serving ).

Which single server container and a single client are you talking about ?

Thanks,
Ajay

**Comment by yunho-oh** [comment]
> Hello @yunho-oh ,
> 
> The cassandra dockerfile does not start the cassandra service.
> This docker image will be used as a base while building other workloads (Ex : Data Serving ).
> 
> Which single server container and a single client are you talking about ?
> 
> Thanks,
> Ajay

I did not include more details in my previous comment. 
Sorry about that.
I tested the data serving workload with this PR and I set a single server-single client configuration.


FYI, I can work on this PR next Tuesday. If you leave any comment or have more updates, I will check them then.

**Comment by ajaygk95** [comment]
> > Hello @yunho-oh ,
> > The cassandra dockerfile does not start the cassandra service.
> > This docker image will be used as a base while building other workloads (Ex : Data Serving ).
> > Which single server container and a single client are you talking about ?
> > Thanks,
> > Ajay
> 
> I did not include more details in my previous comment.
> Sorry about that.
> I tested the data serving workload with this PR and I set a single server-single client configuration.
> 
> FYI, I can work on this PR next Tuesday. If you leave any comment or have more updates, I will check them then.

Hello @yunho-oh ,

Please find my comments below,

1. Add your hostname entry in /etc/hosts (Make sure hostname is pingable) before starting both the containers.

2. After the data-serving server docker, you will be able to see the below logs,

```
   Server IP
   127.0.1.1
   Running Cassandra seed server.
   
   .
   .
   .
   
   .
   .
   
   INFO  [main] 2020-11-13 20:08:56,220 CassandraDaemon.java:556 - Not starting RPC server as requested. Use JMX (StorageService->startRPCServer()) or nodetool (enablethrift) to start it

   INFO  [OptionalTasks:1] 2020-11-13 20:08:58,134 CassandraRoleManager.java:372 - Created default superuser role 'cassandra'
```
  
  Now you can start the data-serving client container

**Comment by yunho-oh** [comment]
Hi,

Thank you for the comment. Please find the following comment of mine.

I have built all the relevant images in a server locally and tried to run the data caching and data serving workloads following the default methodologies described on the CloudSuite website.

First off, the data caching workload has no problem with this PR. It runs well.

Regarding the data serving, it could run with a modification that you introduced (Adding a hostname entry in /etc/hosts).
However, if general users who can see only the manual in the CloudSuite website face the same situation, I think they would have no idea how to solve it.
I would suggest trying to modify the data serving workload issue so we make sure that users do not have to modify the /etc/hosts file.

**Comment by ajaygk95** [comment]
> Hi,
> 
> Thank you for the comment. Please find the following comment of mine.
> 
> I have built all the relevant images in a server locally and tried to run the data caching and data serving workloads following the default methodologies described on the CloudSuite website.
> 
> First off, the data caching workload has no problem with this PR. It runs well.
> 
> Regarding the data serving, it could run with a modification that you introduced (Adding a hostname entry in /etc/hosts).
> However, if general users who can see only the manual in the CloudSuite website face the same situation, I think they would have no idea how to solve it.
> I would suggest trying to modify the data serving workload issue so we make sure that users do not have to modify the /etc/hosts file.


The hostname must be reachable. I am not sure how to fix this from a docker container. I can add a NOTE in data-serving readme about this.
Do you suggest something better on how to fix this in data-serving workload ?

Also this PR has the changes related only to Cassandra and memcached so i guess this PR can be merged.

**Comment by ajaygk95** [comment]
Hello @yunho-oh ,
Any updates on this ?

**Comment by yunho-oh** [comment]
> Hello @yunho-oh ,
> Any updates on this ?

Hi @ajaygk95 

I kindly ask for waiting. 
I am working on five ISCA submissions now.
Also, I keep thinking of how to deal with this PR.

**Comment by yunho-oh** [comment]
> > Hi,
> > Thank you for the comment. Please find the following comment of mine.
> > I have built all the relevant images in a server locally and tried to run the data caching and data serving workloads following the default methodologies described on the CloudSuite website.
> > First off, the data caching workload has no problem with this PR. It runs well.
> > Regarding the data serving, it could run with a modification that you introduced (Adding a hostname entry in /etc/hosts).
> > However, if general users who can see only the manual in the CloudSuite website face the same situation, I think they would have no idea how to solve it.
> > I would suggest trying to modify the data serving workload issue so we make sure that users do not have to modify the /etc/hosts file.
> 
> The hostname must be reachable. I am not sure how to fix this from a docker container. I can add a NOTE in data-serving readme about this.
> Do you suggest something better on how to fix this in data-serving workload ?
> 
> Also this PR has the changes related only to Cassandra and memcached so i guess this PR can be merged.

Adding a note would be necessary.

**Review by yunho-oh — APPROVED** [review]
Please consider adding a note about "what to do if the client of the data serving does not start benchmarking" as another PR.

**Comment by ajaygk95** [comment]
> Please consider adding a note about "what to do if the client of the data serving does not start benchmarking" as another PR.

Hello @yunho-oh ,

I have added a note in readme of data-serving workload as part of #269 .

Please take a look into it.

**Pull request merged**
