### PR TITLE
Instagram/django workload

### PR DESCRIPTION
**Pull request by varun729**
These changes are related to the Instagram-Django workload integration into the Cloudsuite. To set up the Instagram/Django workload.

Note: django-workload uses memcached and cassandra base images of the servers available at cloudsuite/commons before building the application specific images for these servers.

Please refer to the README.md within the benchmarks/django-workload project for detailed steps to setup the django-workload.

### CODE REVIEW

**Comment by Hnefi** [comment]
Hi @varun729, thanks for adding this. We are doing a big CS3 update this week, so we will review this and merge it ASAP!

**Comment by ZiluTian** [comment]
Hi @varun729, I am trying to test out the changes but I got "bad pointer" error upon inspecting the commit (e.g. git log commit-num). I couldn't find the branch that is specified as "jayadevgithub:instagram/django-workload". There is a master branch in django-workload directory at the specified path. It seems that the branch which contained the commit has been deleted. Can you please submit another pull request reflecting this change? Thanks! 

Regards, 
Zilu

**Comment by ZiluTian** [comment]
Hi @varun729, we have updated our componenets (Ubuntu 18.04) which can be found in dev_ARM branch, and it caused some incompatibility when building the cassandra component, e.g. missing packages, due to a different version of Ubuntu (16.04). There are also some minor naming issues regarding the java base image. Can you please update these changes? Thanks!

**Comment by ZiluTian** [comment]
Hi @varun729 , sorry there was some miscommunication within the group. We will update the change and make sure it is compatible. Thanks!

**Comment by Hnefi** [comment]
Hi @varun729, I've changed the base of your PR to point at the dev branch rather than at the master, which we will merge all of the new workloads into for the moment. Don't worry about the conflicts for now, we are going to update the dev branch today with your work on moving memcached and cassandra into /commons, and that should fix them.

Can I ask you guys to use the following feature for documentation? We have a folder called `docs/benchmarks` where we keep all of the *.md files that describe the stages of bringing up and running every workload, as well as what each tier does. This then gets parsed by our TravisCI infrastructure and pushed to the website automatically. Would it be alright for you to move the readme to this directory and add that to the PR? Thanks.

**Comment by ZiluTian** [comment]
Hi @varun729 and @jayadevgithub, I am having a bit trouble with the load generator (siege). The image is built successfully, but when I run run_siege from the siege directory, all the connections are refused and hit percentages are 0. In the log files under /tmp/ directory, there are 5 lines of "IS ASCII: FALSE" followed by all "connection refused". I kept default settings in which docker network=host and target_endpoint=localhost and tried different SIEGE_WORKERS. I also tried the run_containers.sh from the upper directory which uses a designated network with specified IPs and observed the same result. Have you ever encountered this in your development? Do you have any suggestions? Many thanks in advance!

**Comment by ajaygk95** [comment]
Hello @yunho-oh ,

This PR can be closed. Django workload is already merged as part of #265 (merged to dev branch)

Thanks.

**Pull request closed without merging**
