### PR TITLE
Add aarch-64 support

### PR DESCRIPTION
**Pull request by sangnie**

### CODE REVIEW

**Comment by ustiugov** [comment]
Hi Arash! what should we do with this PR?

**Comment by rahulketch** [comment]
I noticed that the only difference between the aarch64 and x86 dockerfiles is the first line (the base image used). Is there a way to make the rest of the parts common so that both files don't need changes in case of bug fixes?

**Comment by neo-apz** [comment]
In some cases, the ARM dockerfile might include a specific way of installing things. Because of that, I don't think we can do it.

There might be a way of having a base file and "include" that base file in the other files. Could you please check to see what we can do about this?

**Comment by sangnie** [comment]
I'm not sure if I was supposed to receive this, but https://stackoverflow.com/questions/32745416/how-to-dynamically-change-the-dockers-base-image may help in cases where just the base image differs.

**Pull request closed without merging**
