### PR TITLE
Add Django workload

### PR DESCRIPTION
**Pull request by alok123t**

### CODE REVIEW

**Comment by neo-apz** [comment]
Please update this PR with the latest changes made to `dev` and update the Travis file.

**Comment by VamshiMuthineni** [comment]
updated with latest changes from dev.

**Comment by pradeepk5** [comment]
Thank you for this pull request. Here are some comments

- Travis entry is not added for this workload. Can we have multi-platform support using buildx?
- Can we use the debian base-os?
- Unlike other workloads, this workload uses scripts for building, deploying containers similar to the original Django repo. However, this workload should adapt the structure of other Cloudsuite workloads (like web-serving, which also have multiple tiers)
- Some files related to data-serving (readme file, dockerfiles) is changed, Is it necessary for this workload? 
- Some files are duplicated in seige and uwsgi folders (like gen-urls-files), Is it necessary? 
- Dockerfile for cassandra 3.11.5 is added but travis entry is missing. Is the specific version of cassandra necessary, If not we can use the common cassandra.

**Comment by pradeepk5** [comment]
When building the cassandra image i get following key error.
```
Err:5 https://dl.bintray.com/apache/cassandra 311x InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY E91335D77E3E87CB
Reading package lists...
W: GPG error: https://dl.bintray.com/apache/cassandra 311x InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY E91335D77E3E87CB
E: The repository 'http://www.apache.org/dist/cassandra/debian 311x InRelease' is not signed.
```

**Comment by neo-apz** [comment]
Any updates on this?
@VamshiMuthineni

**Comment by ajaygk95** [comment]
Hello @neo-apz ,

I am working on this PR now. I am currently making the code changes. Will update the PR soon.

Thanks,
Ajay

**Comment by ajaygk95** [comment]
Hello,

There were some issues while pushing the code to this PR. 

Closing this PR and a new PR is created for the same - https://github.com/parsa-epfl/cloudsuite/pull/265

**Comment by ajaygk95** [comment]
Hello @pradeepk5,

- Travis entry is not added for this workload. Can we have multi-platform support using buildx?

Multi-platform support is added using buildx. I will push the travis file changes once the Facebook PR is merged (This uses siege common image). For testing the images from "ajaygk95" docker repo can be used.

- Can we use the debian base-os?

 All the docker images are now using debian:base-os

- Unlike other workloads, this workload uses scripts for building, deploying containers similar to the original Django repo. However, this workload should adapt the structure of other Cloudsuite workloads (like web-serving, which also have multiple tiers)

The code changes are done. Building and running the Django workload now adapts the same structure as that of other cloudsuite workloads

- Some files related to data-serving (readme file, dockerfiles) is changed, Is it necessary for this workload?

Data-serving files are not included in the new PR

- Some files are duplicated in seige and uwsgi folders (like gen-urls-files), Is it necessary?

Duplicate files have been removed.

- Dockerfile for cassandra 3.11.5 is added but travis entry is missing. Is the specific version of cassandra necessary, If not we can use the common cassandra.

Dockerfile now uses the common cassandra image


All the changes are available as part of - https://github.com/parsa-epfl/cloudsuite/pull/265


Thanks,
Ajay

**Pull request closed without merging**
