### PR TITLE
Updating media-streaming benchmark to use video files instead of text files

### PR DESCRIPTION
**Pull request by varun729**
1. **benchmarks/media-streaming/dataset/Dockerfile**
    - In the docker file, ffmpeg dependency for on-demand video concatenation, to generate the library size of the requested size
    - Added python dependency to run the script which does the video concatenation
    - Added Entrypoint in the dataset creation which handles user parameters
    - Changed the implementation to create the dataset on the host machine instead of creating inside the container
2. **benchmarks/media-streaming/dataset/bootstrap.sh**
    - This Entrypoint script is responsible for reading the user parameters
        a) LIBRARY_SIZE - Library size is given in gigabytes(Entire size of the dataset)
        b) FORCE - this parameter is used force create the new dataset on the host machine ignoring the
already existing dataset on the host machine
3. **benchmarks/media-streaming/dataset/files/VideoSet**
    - Added sample videos from free websites like https://videos.pexels.com/ which are royalty free
4. **benchmarks/media-streaming/dataset/files/filegen/generate_video_files_and_logs.sh**
    - Modified the script to handle the LIBRARY_SIZE requirements of users, based on the requested size of the dataset, the count of videos which gets generated will be modified. The count of videos which gets generated for each resolution is hardcoded for default library size here:
https://github.com/parsa-epfl/cloudsuite/blob/master/benchmarks/media-streaming/dataset/files/filegen/params/240p
5. **benchmarks/media-streaming/dataset/files/filegen/make_zipf.c**
    - Changed the extension of the generated files from .txt to .mp4 as the files will be playable
6. **benchmarks/media-streaming/dataset/files/filegen/video_gen.py**
    - this script reads the video files information(duration, file size) which are generated by the "make_zipf.c " and generate the actual videos using ffmpeg library
7. **benchmarks/media-streaming/server/files/HTMLWebPlayer/**
    - Added HTML Web Player to play the videos from the dataset through a web interface
    - Added Dependencies required for this Web Player to run(html, css, JS files)
8. **benchmarks/media-streaming/server/Dockerfile**
    - Added HTML Web Player directory to the nginx web directory
9. **benchmarks/media-streaming/server/files/nginx.location.append**
    - Modified the Nginx configuration file to serve the HTML Web Player

**Todo**
- Update the Cloudsuite documentation with the updated commands

**Docker Dataset Creation:**
- creating a new dataset
`$ docker run -it --name <container-name> -v /<path-on-host-machine>:/videos <mediastreaming-dataset-image> <size in giga bytes>`

- force creation of dataset by deleting existing dataset
`$ docker run -it -e FORCE=true --name <container-name> -v /<path-on-host-machine>:/videos <mediastreaming-dataset-image> <size-in-gigabytes>`

- ex: create a dataset of 16 gigabytes
`$ docker run -it --name streamingdataset -v /videos:/videos mediastreaming_dataset 16`

- ex: create a dataset of default size (4 Giga Bytes)
`$ docker run -it --name streamingdataset -v /videos:/videos mediastreaming_dataset`

### CODE REVIEW

**Comment by Hnefi** [comment]
Hi @varun729, thanks for the PR. From the text I can see that you have a bunch of stock videos as well as a script to generate larger files using the stock files as a base - is that correct?

If all of the stock videos are needed, can you remove them from being tracked (since they are large binaries) and add them using git LFS?

**Comment by varun729** [comment]
@Hnefi, you are right about larger files getting generated using the stock files.

In the current implementation we are incorrectly trying to use Git LFS (see the file `benchmarks/media-streaming/dataset/files/.gitattributes`).
However, after fixing the .gitattributes file I am unable to push the commit to our repository, which is a public fork of cloudsuite repo, as I get the following error when trying to upload LFS objects:
"batch response: @varun729 can not upload new objects to public fork varun729/cloudsuite"

One way this can be resolved is by doing a commit directly to the cloudsuite repo in a separate branch. You can merge the changes from there.

Do you have any other solutions that we can try?

**Comment by Hnefi** [comment]
Hey Varun, this is because our master doesn't have any LFS objects in it yet. So, public forks cannot push LFS objects. See here: https://github.com/git-lfs/git-lfs/issues/1449

I'll go and migrate one of our datasets to LFS and then you should be able to push the commit.

After I do that, can you please place the files into the top level directory called /datasets? That is where I will initialize git lfs.

**Comment by Hnefi** [comment]
Hey @varun729, we discussed this here recently, and we decided that we are going to move all of the large data files to being hosted directly on our web server at cloudsuite.ch/download.

I've sent instructions to our webmaster and he's going to upload all of your video sets to the url: "cloudsuite.ch/download/media_streaming/VideoSets/" 

Once that's done, would it be alright for you and your team to update the code in this PR to pull the files directly from there?

**Comment by varun729** [comment]
Hi @Hnefi, we can update the code to pull the files directly from the url you provided. Let us know when it is done, so that we can update the PR.

On 2/19/2019 2:46:23 AM, Mark Sutherland <notifications@github.com> wrote:
Hey @varun729 [https://github.com/varun729], we discussed this here recently, and we decided that we are going to move all of the large data files to being hosted directly on our web server at cloudsuite.ch/download.
I've sent instructions to our webmaster and he's going to upload all of your video sets to the url: "cloudsuite.ch/download/media_streaming/VideoSets/"
Once that's done, would it be alright for you and your team to update the code in this PR to pull the files directly from there?

**Comment by Hnefi** [comment]
Hey @varun729, here's the link on our new web server:
http://cloudsuite.ch/download/media_streaming/VideoSet/

thanks again for your all your contributions!

**Comment by varun729** [comment]
Hi @Hnefi, I created a new pull request #218, as I was unable to change the source repository in the pull request.

**Comment by neo-apz** [comment]
@varun729 We merged #218, I'm assuming I should close this pull request, right?

**Comment by varun729** [comment]
@neo-apz Yes, you can close this pull request.

**Pull request closed without merging**
