### PR TITLE
Websearch Update 

### PR DESCRIPTION
**Pull request by komal1204**
Modified client entrypoint.sh to include JAVA_HOME and the latest compiler version so that it builds for ARM and AMD.

### CODE REVIEW

**Comment by komal1204** [comment]
Hello @yunho-oh ,

I made a mistake of creating the pr to the master branch instead of the dev branch. Can you please delete this PR?

Apologies and thanks,
Komal

**Comment by komal1204** [comment]
> Hello @yunho-oh ,
> 
> I made a mistake of creating the pr to the master branch instead of the dev branch. Can you please delete this PR?
> 
> Apologies and thanks,
> Komal

Hello @yunho-oh ,

Please re-trigger the travis build on master branch after deleting this pr.

Thanks again, 
Komal

**Comment by yunho-oh** [comment]
HI @komal1204 

AFAIK, we cannot delete a pull request in Github. 
So, I will leave it without merging it.
If you have a way to do it, please let me know.

**Comment by ajaygk95** [comment]
Hello @yunho-oh ,

Can we retrigger the build for master branch. 
(As this push is not correct, it might affect some docker containers because the docker containers are pushed to cloudsuite repo if the build is on master branch).

**Comment by yunho-oh** [comment]
> Hello @yunho-oh ,
> 
> Can we retrigger the build for master branch. (without including these changes)
> (As this push is not correct, it might affect some docker containers because the docker containers are pushed to cloudsuite repo if the build is on master branch).

I will check the build and re-trigger it late tonight or tomorrow, after I am done with some other tasks.

**Comment by neo-apz** [comment]
Please do not create any pull requests for `master` (you could change this even after it was created), DO NOT trigger the build on `master`, and do not try to change anything related to the `master` branch. This can potentially break our production-ready images on DockerHub.

I'm closing this PR now.

**Comment by komal1204** [comment]
> Please do not create any pull requests for `master` (you could change this to `dev` even after it was created), DO NOT trigger the build on `master`, and do not try to change anything related to the `master` branch. This can potentially break our production-ready images on DockerHub.
> 
> I'm closing this PR now.

Thank you, today I learned something new the hard way.

**Pull request closed without merging**
