### PR TITLE
WebSearch Client Update

### PR DESCRIPTION
**Pull request by komal1204**
Updated compiler version and Java_home for client to java11 so that it builds for ARM and AMD.

### CODE REVIEW

**Comment by komal1204** [comment]
Hello @yunho-oh ,

This is the correct PR for websearch changes, please review this .

Please delete the incorrect PR #274 that i created to the master branch by mistake.

Thanks and Regards ,
Komal

**Comment by komal1204** [comment]
Hello @yunho-oh ,

Can you please review this and ret-rigger the travis build. 

Let me know if there are any other changes to be done.

Thanks ,
Komal

**Comment by yunho-oh** [comment]
Hi @komal1204,

While testing this PR, I am seeing the following error. Please take a look at it.

Buildfile: /usr/src/faban/search/build.xml

init:
    [mkdir] Created dir: /usr/src/faban/search/build/classes

compile:
    [javac] /usr/src/faban/search/build.xml:35: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 1 source file to /usr/src/faban/search/build/classes
    [javac] javac: invalid target release: 11
    [javac] Usage: javac <options> <source files>
    [javac] use -help for a list of possible options

**Comment by komal1204** [comment]
> Hi @komal1204,
> 
> While testing this PR, I am seeing the following error. Please take a look at it.
> 
> Buildfile: /usr/src/faban/search/build.xml
> 
> init:
> [mkdir] Created dir: /usr/src/faban/search/build/classes
> 
> compile:
> [javac] /usr/src/faban/search/build.xml:35: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
> [javac] Compiling 1 source file to /usr/src/faban/search/build/classes
> [javac] javac: invalid target release: 11
> [javac] Usage: javac
> [javac] use -help for a list of possible options

Hello @yunho-oh ,

I used to get that error too, but when i built the faban image from source(in the commons folder), instead of FROM cloudsuite/faban:1.4 which the client dockerfile uses, i didn't get this error. 

So I think this error is because the image on docker hub for faban is not the latest.
image

Similarly, the images for websearch also have not been updated on docker hub.
image

Can you please update these images on dockerhub?

Let me know if you still get the error after building faban from source and using the new faban image in the web search client.

Thanks,
Komal

**Comment by yunho-oh** [comment]
Hi @komal1204,

First of all, if you already saw the error, it would be good if you notice that and let me know what to do (build a separated image without using the image in the docker hub) before you asked me to review this PR.

I will not upload the Faban images right now. 
I have no idea how the uploaded Faban image is used by the existing software stack or internal infrastructures.
Instead, I will test this PR by building a Faban image locally.

**Review by yunho-oh — APPROVED** [review]
This workload should use the new Faban in the common folder.

**Pull request merged**
