### PR TITLE
Webservingupdate to be merged after pr #267

### PR DESCRIPTION
**Pull request by komal1204**
This pr includes the changes to the webserving workload after Mysql(which installs mariadb) is moved to commons. PR #267 
This is done to ensure travis build does not fail as the db_server needs the mysql image.
Please merge this after PR #267 is merged.

### CODE REVIEW

**Comment by yunho-oh** [comment]
Hi @komal1204,

I asked my lab member for the authentication to upload the mariadb image. Will do it asap and then try to do the regression test.

**Comment by yunho-oh** [comment]
> Hi @komal1204,
> 
> I asked my lab member for the authentication to upload the mariadb image. Will do it asap and then try to do the regression test.

I have update the mariadb image and re-run the travisCI.

**Review by yunho-oh — APPROVED** [review]

**Review by yunho-oh — COMMENTED** [review]
Done

**Review by yunho-oh — APPROVED** [review]

**Comment by komal1204** [comment]
Hello @yunho-oh ,

Now we can delete pr #241. 
Also, can the travis build be triggered again, as i see the for pr #267 travis build has failed.

Thanks,
Komal

**Comment by yunho-oh** [comment]
> Hello @yunho-oh ,
> 
> Now we can delete pr #241.
> Also, can the travis build be triggered again, as i see the for pr #267 travis build has failed.
> 
> Thanks,
> Komal

Hello @komal1204 

I am a little confused about what's going on. 
Rather than re-triggering the travis build, can we have a new PR that can fix the build failure? Please let me know your thought.

**Pull request merged**
